### ISSUE TITLE
Write DB entities contract drafts

### ISSUE THREAD

**Issue by aliaksei-lyzo** [aliaksei-lyzo/storm-the-front#20]
Write contract drafts for the following DB entities:
1) Event
2) User
3) News

Keep in mind, please, that users should have a field to describe role or permission, to provide necessary access.

Drafts can be posted on Wiki section of current project

**Comment by mariakravchenko** [comment]
@aliaksei-lyzo  added on wiki page

**Comment by aliaksei-lyzo** [comment]
Closing issue as completed. Great job, @mariakravchenko !
