### ISSUE TITLE
Set up linting on server side

### ISSUE THREAD

**Issue by aliaksei-lyzo** [aliaksei-lyzo/storm-the-front#24]
Set up eslint config on server side, basically, same as client (perhaps extract linting from client to root?)

**Comment by mariakravchenko** [comment]
Stand for separation, it would be easier in the future to separate those project. 
Moreover, we have diff configuration and rules, don't want to mess it up. Ready to listen to any suggestions.
Do you have any experience of how to manage subfolders on parent level efficiently, any concept? I would be grateful if you could share with me
